package y2024

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*

internal class Day8Test {

    val testData = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """.trimIndent().lines()

    @Test
    internal fun partOne() {
        assertEquals(14, y2024.Day8.partOne(testData))
    }

    @Test
    internal fun partTwo() {
        assertEquals(34, y2024.Day8.partTwo(testData))
    }
}