package y2025

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

internal class Day7Test {

    val testData = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """.trimIndent().lines()

    @Test
    internal fun partOne() {
        assertEquals(21L, y2025.Day7.partOne(testData))
    }

    @Test
    internal fun partTwo() {
        assertEquals(40L, y2025.Day7.partTwo(testData))
    }
}